export const assesmentData = [
  {
    id: 1,
    title: "React Fundamentals",
    course: "Full Stack Development",
    trainer: "Trisha Pandey",
    date: "20 Aug 2026",
    duration: "60 min",
    questions: 30,
    status: "Upcoming",
  },
  {
    id: 2,
    title: "JavaScript Basics",
    course: "Web Development",
    trainer: "Avika Mane",
    date: "18 Aug 2026",
    duration: "45 min",
    questions: 25,
    status: "Active",
  },
  {
    id: 3,
    title: "HTML & CSS Assessment",
    course: "Web Development",
    trainer: "Namrata",
    date: "10 Aug 2026",
    duration: "60 min",
    questions: 30,
    status: "Completed",
  },
  {
    id: 4,
    title: "Node.js API Test",
    course: "Full Stack Development",
    trainer: "Dhanashree",
    date: "25 Aug 2026",
    duration: "60 min",
    questions: 35,
    status: "Upcoming",
  },
  {
    id: 5,
    title: "MongoDB Assessment",
    course: "Full Stack Development",
    trainer: "Rahul Varma",
    date: "12 Aug 2026",
    duration: "45 min",
    questions: 25,
    status: "Completed",
  },
];