// src/Info/attendanceData.js

export const traineeAttendanceInfo = {
  traineeId: "TRN001",
  name: "Vaishnavi Kutal",
  course: "Full Stack Development",
  batch: "Batch A",
  minimumRequirement: 75,
};

export const attendanceRecords = [
  {
    id: 1,
    date: "15 Aug 2026",
    rawDate: "2026-08-15",
    session: "React Basics & Hooks",
    course: "Full Stack Development",
    trainer: "Trisha Pandey",
    time: "10:00 AM - 12:00 PM",
    status: "Present",
    month: "August",
  },
  {
    id: 2,
    date: "13 Aug 2026",
    rawDate: "2026-08-13",
    session: "Node.js API Architecture",
    course: "Full Stack Development",
    trainer: "Vaishnavi Kutal",
    time: "11:00 AM - 01:00 PM",
    status: "Absent",
    month: "August",
  },
  {
    id: 3,
    date: "11 Aug 2026",
    rawDate: "2026-08-11",
    session: "Git, GitHub & Version Control",
    course: "Full Stack Development",
    trainer: "Avika Mane",
    time: "10:00 AM - 12:00 PM",
    status: "Late",
    month: "August",
  },
  {
    id: 4,
    date: "09 Aug 2026",
    rawDate: "2026-08-09",
    session: "MongoDB CRUD & Schema",
    course: "Full Stack Development",
    trainer: "Dhanashree",
    time: "02:00 PM - 04:00 PM",
    status: "Present",
    month: "August",
  },
  {
    id: 5,
    date: "05 Aug 2026",
    rawDate: "2026-08-05",
    session: "HTML5 Semantic Elements",
    course: "Full Stack Development",
    trainer: "Namrata",
    time: "10:00 AM - 12:00 PM",
    status: "Leave",
    month: "August",
  },
  {
    id: 6,
    date: "28 Jul 2026",
    rawDate: "2026-07-28",
    session: "CSS Flexbox & Grid Masterclass",
    course: "Full Stack Development",
    trainer: "Namrata",
    time: "10:00 AM - 12:00 PM",
    status: "Present",
    month: "July",
  },
  {
    id: 7,
    date: "24 Jul 2026",
    rawDate: "2026-07-24",
    session: "JavaScript Modern ES6+",
    course: "Full Stack Development",
    trainer: "Avika Mane",
    time: "11:00 AM - 01:00 PM",
    status: "Present",
    month: "July",
  },
];

export const monthlyTrends = [
  { month: "June", percentage: 90 },
  { month: "July", percentage: 88 },
  { month: "August", percentage: 83.3 },
];